server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 799104713761-82uhodh6nnfg661pf74dsqr0521gqtiu.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          facebook:
            client-id: 384534126587070
            client-secret: b59b29421db89a45343c952af25a9ac7
            scope:
            - email
            - public_profile
            
          naver:
            client-id: 9dseq2z2EyrQ1FuXsF2Z
            client-secret: oBIFmepTqc
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 받아옴
            